#!/usr/bin/env python3

import sys
from importlib import import_module
from inspect import signature

name = sys.argv[1]
module = import_module(name)
handler = module.__dict__[name]
sig = signature(handler)
args = ', '.join(map(lambda p: 'inpjs.'+p, sig.parameters))
print('from mate import jso')
print('from ' +name + ' import ' + name)
print('def lambda_handler(input, context):')
print('\tinpjs = jso(input)')
print('\treturn %s(%s)' % (name, args))




